import type { LearnableLessonId, LabId, Lesson } from "./types";
export type LessonSummary = {
  id: LearnableLessonId;
  moduleId: string;
  title: string;
  labId: LabId;
  checkIds: string[];
  subjectiveCheckIds: string[];
};
export const lessonCatalog: LessonSummary[] = [
  {
    id: "A01-A",
    moduleId: "A01",
    title: "收入、财富与“每期”两个字",
    labId: "LA01",
    checkIds: [
      "A01-A-explain",
      "A01-A-number",
      "A01-A-transfer",
      "A01-A-choice",
    ],
    subjectiveCheckIds: ["A01-A-explain", "A01-A-transfer"],
  },
  {
    id: "A01-B",
    moduleId: "A01",
    title: "你的金融资产，往往是别人的负债",
    labId: "LA01",
    checkIds: [
      "A01-B-explain",
      "A01-B-number",
      "A01-B-transfer",
      "A01-B-choice",
    ],
    subjectiveCheckIds: ["A01-B-explain", "A01-B-transfer"],
  },
  {
    id: "A02-A",
    moduleId: "A02",
    title: "GDP不是所有交易金额之和",
    labId: "LA02",
    checkIds: [
      "A02-A-explain",
      "A02-A-number",
      "A02-A-transfer",
      "A02-A-choice",
    ],
    subjectiveCheckIds: ["A02-A-explain", "A02-A-transfer"],
  },
  {
    id: "A02-B",
    moduleId: "A02",
    title: "恒等式不会替你回答因果问题",
    labId: "LA02",
    checkIds: [
      "A02-B-explain",
      "A02-B-number",
      "A02-B-transfer",
      "A02-B-choice",
    ],
    subjectiveCheckIds: ["A02-B-explain", "A02-B-transfer"],
  },
  {
    id: "A03-A",
    moduleId: "A03",
    title: "同样的数字增长，可能是不同的世界",
    labId: "LA03",
    checkIds: [
      "A03-A-explain",
      "A03-A-number",
      "A03-A-transfer",
      "A03-A-choice",
    ],
    subjectiveCheckIds: ["A03-A-explain", "A03-A-transfer"],
  },
  {
    id: "A03-B",
    moduleId: "A03",
    title: "通胀下降不等于价格下降",
    labId: "LA03",
    checkIds: [
      "A03-B-explain",
      "A03-B-number",
      "A03-B-transfer",
      "A03-B-choice",
    ],
    subjectiveCheckIds: ["A03-B-explain", "A03-B-transfer"],
  },
  {
    id: "A04-A",
    moduleId: "A04",
    title: "多一台设备，为什么不总多出同样的产量？",
    labId: "LA04",
    checkIds: [
      "A04-A-explain",
      "A04-A-number",
      "A04-A-transfer",
      "A04-A-choice",
    ],
    subjectiveCheckIds: ["A04-A-explain", "A04-A-transfer"],
  },
  {
    id: "A04-B",
    moduleId: "A04",
    title: "到达更高的平台，不等于永远跑得更快",
    labId: "LA04",
    checkIds: [
      "A04-B-explain",
      "A04-B-number",
      "A04-B-transfer",
      "A04-B-choice",
    ],
    subjectiveCheckIds: ["A04-B-explain", "A04-B-transfer"],
  },
  {
    id: "A05-A",
    moduleId: "A05",
    title: "发明出现了，生产率为什么未必立刻提高？",
    labId: "LA04",
    checkIds: [
      "A05-A-explain",
      "A05-A-number",
      "A05-A-transfer",
      "A05-A-choice",
    ],
    subjectiveCheckIds: ["A05-A-explain", "A05-A-transfer"],
  },
  {
    id: "A05-B",
    moduleId: "A05",
    title: "平均更富，为什么有些人仍未受益？",
    labId: "LA04",
    checkIds: [
      "A05-B-explain",
      "A05-B-number",
      "A05-B-transfer",
      "A05-B-choice",
    ],
    subjectiveCheckIds: ["A05-B-explain", "A05-B-transfer"],
  },
  {
    id: "A06-A",
    moduleId: "A06",
    title: "大家都想多存一点，为什么收入也会变？",
    labId: "LA05",
    checkIds: [
      "A06-A-explain",
      "A06-A-number",
      "A06-A-transfer",
      "A06-A-choice",
    ],
    subjectiveCheckIds: ["A06-A-explain", "A06-A-transfer"],
  },
  {
    id: "A06-B",
    moduleId: "A06",
    title: "利率改变了，投资为什么不必照着按钮走？",
    labId: "LA05",
    checkIds: [
      "A06-B-explain",
      "A06-B-number",
      "A06-B-transfer",
      "A06-B-choice",
    ],
    subjectiveCheckIds: ["A06-B-explain", "A06-B-transfer"],
  },
  {
    id: "A07-A",
    moduleId: "A07",
    title: "没工作的人，为什么不全算失业？",
    labId: "LA06",
    checkIds: [
      "A07-A-explain",
      "A07-A-number",
      "A07-A-transfer",
      "A07-A-choice",
    ],
    subjectiveCheckIds: ["A07-A-explain", "A07-A-transfer"],
  },
  {
    id: "A07-B",
    moduleId: "A07",
    title: "需求、成本与预期：同是涨价，机制不同",
    labId: "LA06",
    checkIds: [
      "A07-B-explain",
      "A07-B-number",
      "A07-B-transfer",
      "A07-B-choice",
    ],
    subjectiveCheckIds: ["A07-B-explain", "A07-B-transfer"],
  },
  {
    id: "A08-A",
    moduleId: "A08",
    title: "贷款、跨行支付与损失：三种不同的记账",
    labId: "LA07",
    checkIds: [
      "A08-A-explain",
      "A08-A-number",
      "A08-A-transfer",
      "A08-A-choice",
    ],
    subjectiveCheckIds: ["A08-A-explain", "A08-A-transfer"],
  },
  {
    id: "A08-B",
    moduleId: "A08",
    title: "利率、预期与资产购买：工具如何到达结果",
    labId: "LA06",
    checkIds: [
      "A08-B-explain",
      "A08-B-number",
      "A08-B-transfer",
      "A08-B-choice",
    ],
    subjectiveCheckIds: ["A08-B-explain", "A08-B-transfer"],
  },
  {
    id: "A09-A",
    moduleId: "A09",
    title: "购买、转移与税收：财政如何影响需求和分配",
    labId: "LA08",
    checkIds: [
      "A09-A-explain",
      "A09-A-number",
      "A09-A-transfer",
      "A09-A-choice",
    ],
    subjectiveCheckIds: ["A09-A-explain", "A09-A-transfer"],
  },
  {
    id: "A09-B",
    moduleId: "A09",
    title: "债务率的分子、分母与精确递推",
    labId: "LA08",
    checkIds: [
      "A09-B-explain",
      "A09-B-number",
      "A09-B-transfer",
      "A09-B-choice",
    ],
    subjectiveCheckIds: ["A09-B-explain", "A09-B-transfer"],
  },
  {
    id: "A10-A",
    moduleId: "A10",
    title: "贸易之外的另一侧：经常账户与外部净资产",
    labId: "LA09",
    checkIds: [
      "A10-A-explain",
      "A10-A-number",
      "A10-A-transfer",
      "A10-A-choice",
    ],
    subjectiveCheckIds: ["A10-A-explain", "A10-A-transfer"],
  },
  {
    id: "A10-B",
    moduleId: "A10",
    title: "汇率是一个比价，贸易响应需要另一套机制",
    labId: "LA09",
    checkIds: [
      "A10-B-explain",
      "A10-B-number",
      "A10-B-transfer",
      "A10-B-choice",
    ],
    subjectiveCheckIds: ["A10-B-explain", "A10-B-transfer"],
  },
  {
    id: "A11-A",
    moduleId: "A11",
    title: "杠杆与期限：有资产为何也会付不出钱？",
    labId: "LA07",
    checkIds: [
      "A11-A-explain",
      "A11-A-number",
      "A11-A-transfer",
      "A11-A-choice",
    ],
    subjectiveCheckIds: ["A11-A-explain", "A11-A-transfer"],
  },
  {
    id: "A11-B",
    moduleId: "A11",
    title: "金融与实体：比较箭头，不把三个模型拼成预测",
    labId: "LA05",
    checkIds: [
      "A11-B-explain",
      "A11-B-number",
      "A11-B-transfer",
      "A11-B-choice",
    ],
    subjectiveCheckIds: ["A11-B-explain", "A11-B-transfer"],
  },
  {
    id: "A12-A",
    moduleId: "A12",
    title: "看见共变之后：反事实、识别与数据版本",
    labId: "LA06",
    checkIds: [
      "A12-A-explain",
      "A12-A-number",
      "A12-A-transfer",
      "A12-A-choice",
    ],
    subjectiveCheckIds: ["A12-A-explain", "A12-A-transfer"],
  },
  {
    id: "A12-B",
    moduleId: "A12",
    title: "终课作品：一份有机制、有账本、有证据边界的诊断",
    labId: "LA06",
    checkIds: [
      "A12-B-explain",
      "A12-B-number",
      "A12-B-transfer",
      "A12-B-choice",
    ],
    subjectiveCheckIds: ["A12-B-explain", "A12-B-transfer"],
  },
];
const loaders: Record<string, () => Promise<{ lessons: Lesson[] }>> = {
  A01: () => import("./modules/A01"),
  A02: () => import("./modules/A02"),
  A03: () => import("./modules/A03"),
  A04: () => import("./modules/A04"),
  A05: () => import("./modules/A05"),
  A06: () => import("./modules/A06"),
  A07: () => import("./modules/A07"),
  A08: () => import("./modules/A08"),
  A09: () => import("./modules/A09"),
  A10: () => import("./modules/A10"),
  A11: () => import("./modules/A11"),
  A12: () => import("./modules/A12"),
};
export async function loadLesson(id: string): Promise<Lesson | undefined> {
  const module = id.slice(0, 3);
  if (!loaders[module]) return undefined;
  return (await loaders[module]()).lessons.find((lesson) => lesson.id === id);
}
